### ISSUE TITLE
You are awesome but...

### ISSUE THREAD

**Issue by ghost** [diessica/elementaryos-essentials#1]
dont need
- sudo add-apt-repository ppa:otto-kesselgulasch/gimp
- sudo add-get-repository ppa:renbag/ppa

also

dont work
- curl -O https://raw.github.com/diessica/elementaryos-essentials/master/kit.sh
  - *downloaded a empty file* :1234: 
- sudo apt-get install AcetoneISO-6.7.deb
  - *E: The AcetoneISO-6.7.deb package could not be located
E: No package could be found using «*» with «AcetoneISO-6.7.deb»
E: Could not find any package with the regular expression «AcetoneISO-6.7.deb»*
- sudo apt-get install kommander p7zip
  -*The kommander package is not available, but some other package makes reference
to the. This may mean that the package is missing, obsolete or only
find available from some other source*
 
I hope I'm wrong. Thank you as always, Diéssica.

Everything else 10/10.

**Comment by diessica** [comment]
awww, thank you <3

I've updated it accordingly :) I don't use eOS anymore though, hence the outdated repo!
